<div class="entry-edit">
	<fieldset>
		<ul class="note-list">
			<?php foreach($this->getLogCollection() as $_log):?>
				<li><strong><?php echo Mage::getModel('core/date')->date($_log->getCreateAt()); ?></strong>
				<span class="separator">|</span>
				<strong><?php echo $_log->getCreateFrom(); ?></strong>
				<span class="separator">|</span>
				<strong class="subdue"><?php echo $_log->getLogText(); ?></strong>
				<?php if($_log->getComment() != ""): ?>
				<span class="separator">|</span>
				<strong><?php echo $_log->getComment(); ?></strong>
				<?php endif; ?>
				</li>
			<?php endforeach; ?>
		</ul>
	</fieldset>
</div>