<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Rma
 * @version    1.3.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
?>
<div class="entry-edit">
<?php if ($this->getOrder()) : ?>
	<div class="entry-edit-head">
		<h4><?php echo $this->__('Items RMA Requested for') ?></h4>
	</div>
    <div class="grid">
        <table class="data border" cellpadding="0" cellspacing="0" id="rma_itmes">
            <col />
            <col width="1" />
            <col width="1" />
			<col width="1" />
            <thead>
                <tr class="headings">
                    <th><?php echo $this->__('Product Name') ?></th>
                    <th><?php echo $this->__('SKU') ?></th>
                    <th><?php echo $this->__('Qty') ?></th>
                    <th><?php echo $this->__('Return to Stock') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php $requestedItems = $this->getRmaRequest()->getOrderItems() ?>
                <?php foreach (Mage::helper('awrma')->getItemsHtml($this->getRmaRequest(), array('items' => array_keys($requestedItems))) as $item) : ?>
                    <?php echo $item ?>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
	<?php if($this->getRmaRequest()->getStatus() <= 3 || $this->getRmaRequest()->getStatus() >= 7): ?>
			<?php if($this->getRmaRequest()->getCreditMemoId() == null || $this->getRmaRequest()->getCreditMemoId() == "" ): ?>
			<!-- 客服审批金额，并不生成 credit memon -->
			<div class="entry-edit-head">
				<h4><?php echo $this->__('Accraditation Credit Memon Settings') ?></h4>
			</div>
			<?php $accraditation_amount_array = Mage::helper('rmaddon')->getRmaRefundInitAmount($this->getRmaRequest()->getId(), $this->getOrder()->getId()); ?>
			<div class="fieldset" id="accraditation">
				<div class="hor-scroll">
					<table class="form-list">
						<tr>
							<td class="label"><label for="accraditation_refund_shipping"><?php echo $this->__('Refund Shipping');?></label></td>
							<td class="value"><input id="accraditation_refund_shipping" class="input-text" type="text" value="<?php echo $accraditation_amount_array['shipping_amount']; ?>" /></td>
						</tr>
						<tr>
							<td class="label"><label for="accraditation_products_amount"><?php echo $this->__('Refund Products');?></label></td>
							<td class="value"><input id="accraditation_products_amount" class="input-text" type="text" value="<?php echo $accraditation_amount_array['products_amount']?>"  /></td>
						</tr>
						<tr>
							<td class="label"><label for="products_amount"><?php echo $this->__('Refund Products Tip Info');?></label></td>
							<td class="value"><label style="color:red"><?php echo Mage::helper('rmaddon')->getRefundAmountTip($this->getRmaRequest()->getId(), $this->getOrder()->getId()); ?></label></td>
						</tr>
					</table>
				</div>
				<button type="button" class="scalable scalable save" id="accraditation_refund_button"><span><span><span><?php echo $this->__('Accraditation'); ?></span></span></span></button>
			</div>
			<script type="text/javascript">
			  jQuery(document).ready(function($){
				$('#accraditation_refund_button').click(function(){
					var max_amount = <?php echo Mage::helper('rmaddon')->getRefundAmountTip($this->getRmaRequest()->getId(), $this->getOrder()->getId()); ?>;
					var refund_accraditation_products_amount = $('#accraditation_products_amount').val();
					if(refund_accraditation_products_amount <= max_amount){
						$.ajax({
							url : '<?php echo Mage::helper("adminhtml")->getUrl("rmaddon/adminhtml_ajax/ajaxAccraditationRefund"); ?>',
							data : {
								form_key : window.FORM_KEY,
								rma_id : <?php echo $this->getRmaRequest()->getId(); ?>,
								order_id : <?php echo $this->getOrder()->getId(); ?>,
								refund_accraditation_shipping_amount : $('#accraditation_refund_shipping').val(),
								refund_accraditation_products_amount : refund_accraditation_products_amount
							},
							type:'post',    
							cache:false,    
							dataType:'json',
							success:function(data) {
								if(data.status){
									window.location.reload();
								}
							},    
							error:function(){
								alert('Error, Please Check Params');
							}
						});
					}else{
						alert('<?php echo $this->__('Max Amount %s', Mage::helper('rmaddon')->getRefundAmountTip($this->getRmaRequest()->getId(), $this->getOrder()->getId())); ?>');
					}
				})
			  });
			</script>
			<?php else: ?>
				<div class="fieldset ">
					<div class="hor-scroll">
						<table class="form-list">
							<tbody>
								<tr>
									<td class="label"><label><?php echo $this->__('Credit Memo');?></label></td>
									<td class="value"><?php echo Mage::helper('rmaddon')->getCreditMemo($this->getRmaRequest()->getCreditMemoId()); ?></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			<?php endif; ?>
	<div class="entry-edit-head">
		<h4><?php echo $this->__('Credit Memon Settings') ?></h4>
	</div>
	<?php if($this->getRmaRequest()->getCreditMemoId() == null || $this->getRmaRequest()->getCreditMemoId() == "" ){ ?>
	<!-- 财务审批并生成 credit memon -->
	<?php $refund_amount_array = Mage::helper('rmaddon')->getRmaRefundInitAmount($this->getRmaRequest()->getId(), $this->getOrder()->getId()); ?>
	<div id="credit_memon" class="fieldset ">
		<div class="hor-scroll">
			<table class="form-list">
				<tbody>
					<tr>
						<td class="label"><label for="refund_shipping"><?php echo $this->__('Refund Shipping');?></label></td>
						<td class="value"><input id="refund_shipping" class="input-text" type="text" value="<?php echo $refund_amount_array['shipping_amount']; ?>" name="credit[shipping_amount]" /></td>
					</tr>
					<tr>
						<td class="label"><label for="products_amount"><?php echo $this->__('Refund Products');?></label></td>
						<td class="value"><input id="products_amount" class="input-text" type="text" value="<?php echo $refund_amount_array['products_amount']; ?>" name="credit[products_amount]" /></td>
					</tr>
					<tr>
						<td class="label"><label for="products_amount"><?php echo $this->__('Refund Products Tip Info');?></label></td>
						<td class="value"><label style="color:red"><?php echo Mage::helper('rmaddon')->getRefundAmountTip($this->getRmaRequest()->getId(), $this->getOrder()->getId()); ?></label></td>
					</tr>
				</tbody>
			</table>
		</div>
		<!--  客服不审批，财务不允许直接退款 -->
		<?php if(Mage::helper('rmaddon')->isExamine($this->getRmaRequest()->getId(), $this->getOrder()->getId())): ?>
			<button type="button" class="scalable scalable save" id="refund_button"><span><span><span><?php echo $this->__('Refund'); ?></span></span></span></button>
		<?php else: ?>
			<div class="tip"><span style="color:red"><?php echo $this->__('Customer service is not for approval'); ?></span></div>
		<?php endif; ?>
	</div>
	<?php if(Mage::helper('rmaddon')->isExamine($this->getRmaRequest()->getId(), $this->getOrder()->getId())): ?>
	<script type="text/javascript">
		jQuery(document).ready(function($){
			var rma_id = <?php echo $this->getRmaRequest()->getId(); ?>;
			var order_id = <?php echo $this->getOrder()->getId(); ?>;
			var _amount = <?php echo Mage::helper('rmaddon')->getRefundAmountTip($this->getRmaRequest()->getId(), $this->getOrder()->getId()); ?>;
			$('#refund_button').click(function(){
				$('#content p.form-buttons').remove();
				var items_array = new Array();
				var refund_shipping_amount = $('#refund_shipping').val();
				var refund_products_amount = $('#products_amount').val();
				var form_key = window.FORM_KEY;
				var ajax_url = '<?php echo Mage::helper("adminhtml")->getUrl("rmaddon/adminhtml_ajax/ajaxRefund");?>';
				$('.awrma-items-count').each(function(index){
					items_array[$(this).attr('id').replace('orderitem-count', '' )] = $('.returnstock-items-count:eq(' + index + ')').val();
					
				});
				
				if(refund_products_amount <= _amount){
					$.ajax({
						url : ajax_url,
						data : {
							form_key : form_key,
							items : items_array,
							rma_id : rma_id,
							order_id : order_id,
							refund_shipping_amount : refund_shipping_amount,
							refund_products_amount : refund_products_amount
						},
						type:'post',    
						cache:false,    
						dataType:'json',
						success:function(data) {
							if(data.txt != ""){
								alert(data.txt);
								window.location.reload();
							}
						},    
						error:function(){
							alert('Error, Please Check Params');
						}
					});
				}else{
					alert('<?php echo $this->__('Max Amount %s', Mage::helper('rmaddon')->getRefundAmountTip($this->getRmaRequest()->getId(), $this->getOrder()->getId())); ?>');
				}
			
			})
		});
	</script>
	<?php endif; ?>
	
	
	
	<?php }else{ ?>
		<div class="fieldset ">
			<div class="hor-scroll">
			<table class="form-list">
				<tbody>
					<tr>
						<td class="label"><label><?php echo $this->__('Credit Memo');?></label></td>
						<td class="value"><a target="_blank" href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/sales_creditmemo/view/", array('creditmemo_id' => $this->getRmaRequest()->getCreditMemoId()));?>"><?php echo Mage::helper('rmaddon')->getCreditMemo($this->getRmaRequest()->getCreditMemoId()); ?></a></td>
					</tr>
				</tbody>
			</table>
		</div>
		</div>
	<?php } ?>
	<?php endif; ?>
<?php else : ?>
    <?php echo $this->__('Couldn\'t load order') ?>
<?php endif ?>
</div>